<?php

/**
 * CmsPage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class CmsPage extends BaseCmsPage
{
    
    public function setUp()
    {
        $this->hasMutator('route', 'emptyStringToNull');
    }
    
    public function emptyStringToNull($route)
    {
        $this->_set('route', empty($route) ? null : $route);
    }
}
