<?php

/**
 * Confirmation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Confirmation extends BaseConfirmation
{
    protected $_entity;
    
    public function setUp()
    {
        parent::setUp();
        $this->hasAccessor('Entity', '_getEntity');
    }
    
    protected function _getEntity()
    {
        if(is_null($this->_entity)) {
            $this->_entity = Doctrine::getTable($this->entity_model)->find($this->entity_id);
        }
        
        return $this->_entity;
    }
}
