production: 
  phpSettings: 
    display_startup_errors: 0
    display_errors: 0
  includePaths: 
    library: APPLICATION_PATH/../library
  bootstrap: 
    path: APPLICATION_PATH/Bootstrap.php
    class: Bootstrap
  resources: 
    frontController: 
      controllerDirectory: APPLICATION_PATH/controllers
      moduleDirectory: APPLICATION_PATH/modules
      moduleControllerDirectoryName: controllers
    modules: 
      - 
    layout: 
      layoutPath: APPLICATION_PATH/layouts
    view: 
      encoding: UTF-8
  locale: en
  doctrine: 
    data_fixtures_path: APPLICATION_PATH/../doctrine/data/fixtures
    migrations_path: APPLICATION_PATH/../doctrine/migrations
    sql_path: APPLICATION_PATH/../doctrine/data/sql
    yaml_schema_path: APPLICATION_PATH/../doctrine/schema
    models_path: APPLICATION_PATH/../doctrine/models
  rules: 
    default_behavior: 1

staging: 
  _extends: production

testing: 
  phpSettings: 
    display_startup_errors: 1
    display_errors: 1
  _extends: production
development: 
  phpSettings: 
    display_startup_errors: 1
    display_errors: 1
  config: APPLICATION_PATH/configs/application.local.yaml
  _extends: production
