default:
  rule: _TRUE_
  children:
    index:
      rule: _TRUE_
      children:
        index:
          rule: _TRUE_
    error:
      rule: _TRUE_
      children:
        error:
          rule: _TRUE_