Request:    
  default-error-error: {rule: _TRUE_}
  default-index-index: {rule: _TRUE_}
  user-index-index: {rule: user_logged_in_or_in_params, handler: not_detected_user}
  user-auth-login: {rule: !logged_in, handler: forbiden}
  user-auth-logout: {rule: logged_in, handler: forbiden}
  user-register-register: {rule: !logged_in, handler: forbiden}  
