Request:    
  default-error-error: {rule: _TRUE_}
  default-index-index: {rule: _TRUE_}
  
  admin-index-index: {rule: admin_logged_in, handler: not_detected_admin}
  admin-auth-login: {rule: !admin_logged_in, handler: forbidden}
  admin-auth-logout: {rule: admin_logged_in, handler: forbidden}
  
  admin-cms-index: {rule: admin_logged_in, handler: not_detected_admin}
  admin-cms-add-page: {rule: admin_logged_in, handler: not_detected_admin}
  admin-cms-edit-page: {rule: allowed_edit_cms_page, handler: not_found_if_admin_authorized}
  
  cms-index-index: {rule: cms_page_exists, handler: not_found} 
