Request:    
  default-error-error: {rule: _TRUE_}
  default-index-index: {rule: _TRUE_}
  user-index-index: {rule: user_logged_in_or_in_params, handler: not_detected_user}
  user-auth-login: {rule: allowed_to_auth, handler: redirect_to_user_index}
  user-auth-logout: {rule: _TRUE_}
  user-register-register: {rule: !logged_in, handler: redirect_to_user_index}

  user-auth-forgot-password: {rule: !logged_in, handler: forbidden}
  user-auth-forgot-password-mail-sent: {rule: not_logged_in_and_forgot_pswd_hash, handler: not_found}
  
  confirmation-index-accept: {rule: hash_exist, handler: not_found}
  confirmation-index-decline: {rule: hash_exist, handler: not_found}
  
  confirmation-user-forgot-password: {rule: not_logged_in_and_forgot_pswd_hash_exist, handler: not_found}
