User:
  user_in_params:
    type: FUNC
  user_exist:
    type: FUNC
  logged_in:
    type: FUNC

Admin:
  admin_logged_in:
    type: AND
    dependences: [logged_in]
  allowed_edit_cms_page:
    type: AND
    dependences: [admin_logged_in, cms_page_exists]
  cms_page_exists:
    type: FUNC
