User:
  user_logged_in_or_in_params:
    type: OR
    dependences: [real_user_in_params, no_user_in_params_and_logged_in]
  real_user_in_params:
    type: AND
    dependences: [user_in_params, user_exist]
  no_user_in_params_and_logged_in:
    type: AND
    dependences: [!user_in_params, logged_in]
  user_in_params:
    type: FUNC
  user_exist:
    type: FUNC
  logged_in:
    type: FUNC

Admin:
  admin_logged_in:
    type: AND
    dependences: [logged_in]
  allowed_edit_cms_page:
    type: AND
    dependences: [admin_logged_in, cms_page_exists]
  allowed_add_cms_page:
    type: AND
    dependences: [admin_logged_in, add_page_allowed]
  allowed_delete_cms_page:
    type: AND
    dependences: [admin_logged_in, delete_page_allowed, cms_page_exists]  
  cms_page_exists:
    type: FUNC
  add_page_allowed:
    type: FUNC
  edit_page_allowed:
    type: FUNC
  delete_page_allowed:
    type: FUNC
  change_page_name_allowed:
    type: FUNC
  change_page_route_allowed:
    type: FUNC
    
