User:
  user_logged_in_or_in_params:
    type: OR
    dependences: [real_user_in_params, no_user_in_params_and_logged_in]
  real_user_in_params:
    type: AND
    dependences: [user_in_params, user_exist]
  no_user_in_params_and_logged_in:
    type: AND
    dependences: [!user_in_params, logged_in]
  user_in_params:
    type: FUNC
  user_exist:
    type: FUNC
  logged_in:
    type: FUNC
  allowed_to_auth:
    type: OR
    dependences: [!logged_in, is_post]
  is_post:
    type: FUNC
  not_logged_in_and_forgot_pswd_hash:
    type: AND
    dependences: [!logged_in, forgot_pswd_hash]
  forgot_pswd_hash:
    type: FUNC    

Confirmation:
  hash_exist:
    type: FUNC
  not_logged_in_and_forgot_pswd_hash_exist:
    type: AND
    dependences: [!logged_in, forgot_pswd_hash] 
