<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html> 
<head>  
    <?=$this->headMeta()->appendHttpEquiv('Content-Type', 
        'text/html; charset=utf-8')?>
    <?=$this->headTitle('Project Name')?>
    <base href="<?=BASE_PATH?>" />
    <?=$this->headLink();?>
    <?=$this->headScript()
        ->prependFile('/scripts/jquery.min.js');?>
</head> 
<body>